# Generated by Django 4.2.20 on 2025-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rnc', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(max_length=50)),
                ('terminos_pago', models.CharField(choices=[('contado', 'Contado'), ('15dias', '15 días'), ('30dias', '30 días'), ('45dias', '45 días'), ('60dias', '60 días')], default='30dias', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Suplidores',
                'db_table': 'suplidores',
            },
        ),
    ]
