# Generated by Django 4.2.20 on 2025-10-30 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_suplidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('producto', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Fertilizantes Nitrogenados', 'Fertilizantes Nitrogenados'), ('Fertilizantes Fosfatados', 'Fertilizantes Fosfatados'), ('Fertilizantes Potásicos', 'Fertilizantes Potásicos'), ('Fertilizantes Compuestos', 'Fertilizantes Compuestos'), ('Fertilizantes Orgánicos', 'Fertilizantes Orgánicos'), ('Micronutrientes', 'Micronutrientes')], max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('ton', 'Toneladas (ton)'), ('L', 'Litros (L)'), ('unidad', 'Unidades'), ('saco', 'Sacos')], max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta1_con_itbis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta2_con_itbis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta3_con_itbis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('itbis_porcentaje', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.suplidor')),
            ],
            options={
                'verbose_name': 'Entrada de Producto',
                'verbose_name_plural': 'Entradas de Productos',
            },
        ),
    ]
