# Generated by Django 4.2.20 on 2025-10-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_entradaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
