# Generated by Django 4.2.20 on 2025-10-31 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_entradaproducto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaproducto',
            name='numero_factura',
        ),
    ]
