# Generated by Django 4.2.20 on 2025-10-31 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_remove_entradaproducto_numero_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100, unique=True)),
                ('fecha_factura', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('condicion', models.CharField(choices=[('Contado', 'Contado'), ('Crédito', 'Crédito')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Vencido', 'Vencido')], default='Pendiente', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('suplidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.suplidor')),
            ],
            options={
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-fecha_factura'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.entradaproducto')),
            ],
            options={
                'db_table': 'detalle_compra',
            },
        ),
    ]
