# Generated by Django 4.2.20 on 2025-10-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_compra_detallecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
