# Generated by Django 4.2.20 on 2025-11-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_cuentaporcobrar_pagocuentacobrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente Pagada'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=20),
        ),
    ]
