# Generated by Django 4.2.20 on 2025-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_alter_cuentaporcobrar_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('anulada', 'Anulada')], default='activa', max_length=10),
        ),
    ]
