# Generated by Django 4.2.20 on 2025-11-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuentacobrar',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('anulado', 'Anulado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='pagocuentacobrar',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagocuentacobrar',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
