# Generated by Django 4.2.20 on 2025-11-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_pagocuentacobrar_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuentacobrar',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
