# Generated by Django 4.2.20 on 2025-11-17 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_pagocuentacobrar_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devolucion', models.CharField(max_length=50, unique=True)),
                ('fecha_devolucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('motivo', models.CharField(choices=[('defective', 'Producto defectuoso'), ('wrong_item', 'Artículo incorrecto'), ('not_as_described', 'No coincide con la descripción'), ('damaged', 'Producto dañado'), ('customer_change', 'Cambio de opinión del cliente'), ('other', 'Otro motivo')], max_length=50)),
                ('comentarios', models.TextField(blank=True)),
                ('total_devolucion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='facturacion.venta')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.detalleventa')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.entradaproducto')),
            ],
        ),
    ]
