# Generated by Django 4.2.20 on 2025-11-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_devolucion_itemdevolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
