# Generated by Django 4.2.20 on 2025-11-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_venta_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
