# Generated by Django 4.2.20 on 2025-11-20 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_venta_cliente_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagocuentacobrar',
            options={'verbose_name': 'Pago de cuenta por cobrar', 'verbose_name_plural': 'Pagos de cuentas por cobrar'},
        ),
        migrations.AlterField(
            model_name='pagocuentacobrar',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagocuentacobrar',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
