# Generated by Django 4.2.20 on 2026-04-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_alter_pagocuentacobrar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaproducto',
            name='precio_venta2',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='precio_venta2_con_itbis',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='precio_venta3',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='precio_venta3_con_itbis',
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
