# Generated by Django 4.2.20 on 2026-05-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_remove_entradaproducto_precio_venta2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
